.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <displayFormat>ID-{0000}</displayFormat>
        <label>AccountID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>ID</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>ORDRID</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <label>ProductID</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>PRODID</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/orderController.cls
public with sharing class orderController {
	@AuraEnabled
	public static void createOrderAndOrderItems(Decimal totalPrice, Integer totalProductCount) {

		Account account = [SELECT AccountID__c FROM Account LIMIT 1];



		Order__c order = new Order__c();
		order.Name = generateOrderId();
		order.AccountID__c = account.ID;
		order.TotalPrice__c = totalPrice;
		order.TotalProductCount__c = totalProductCount;
		insert order;


		List<Product__c> selectedProducts = [SELECT Id, Price__c FROM Product__c];


		List<OrderItem__c> orderItems = new List<OrderItem__c>();

		for (Product__c product : selectedProducts) {
			OrderItem__c orderItem = new OrderItem__c();
			orderItem.OrderId__c = order.Id;
			orderItem.ProductID__c = product.Id;
			orderItem.Quantity__c = 1;
			orderItem.Price__c = product.Price__c;
			orderItems.add(orderItem);
		}

		insert orderItems;
	}

	private static String generateOrderId() {
		return 'ORD-' + String.valueOf(System.currentTimeMillis());
	}
}