.apex/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <displayFormat>ID-{0000}</displayFormat>
        <label>AccountID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>ID</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>ORDRID</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <label>ProductID</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>PRODID</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/orderControllerTest.cls
@isTest
public class orderControllerTest {
	@isTest
	static void testCreateOrderAndOrderItems() {
		// Создаем тестовые данные
		Account testAccount = new Account();
		testAccount.Name = 'Test Account';
		insert testAccount;

		Product__c testProduct = new Product__c();
		testProduct.Name = 'Test Product';
		testProduct.Price__c = 10;
		insert testProduct;

		// Вызываем метод, который нужно протестировать
		orderController.createOrderAndOrderItems(100, 5);

		// Проверяем созданный заказ
		List<Order__c> orders = [SELECT Id, Name, AccountID__c, TotalPrice__c, TotalProductCount__c FROM Order__c];
		System.assertEquals(1, orders.size());
		Order__c createdOrder = orders[0];
		System.assertEquals('ORD-', createdOrder.Name.substring(0, 4));
		System.assertEquals(testAccount.Id, createdOrder.AccountID__c);
		System.assertEquals(100, createdOrder.TotalPrice__c);
		System.assertEquals(5, createdOrder.TotalProductCount__c);

		// Проверяем созданные элементы заказа
		List<OrderItem__c> orderItems = [SELECT Id, OrderId__c, ProductID__c, Quantity__c, Price__c FROM OrderItem__c];
		System.assertEquals(1, orderItems.size());
		OrderItem__c createdOrderItem = orderItems[0];
		System.assertEquals(createdOrder.Id, createdOrderItem.OrderId__c);
		System.assertEquals(testProduct.Id, createdOrderItem.ProductID__c);
		System.assertEquals(1, createdOrderItem.Quantity__c);
		System.assertEquals(testProduct.Price__c, createdOrderItem.Price__c);
	}
}