src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family 1</fullName>
                </value>
                <value>
                    <fullName>Family 2</fullName>
                </value>
                <value>
                    <fullName>Family 3</fullName>
                </value>
                <value>
                    <fullName>Family 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type 1</fullName>
                </value>
                <value>
                    <fullName>Type 2</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/orderFilter.cls
public class orderFilter {
	@AuraEnabled(cacheable=true)
	public static List<String> getProductTypes() {
		List<String> types = new List<String>();
		List<Schema.PicklistEntry> picklistValues = Product__c.Type__c.getDescribe().getPicklistValues();

		for (Schema.PicklistEntry picklistValue : picklistValues) {
			types.add(picklistValue.getValue());
		}

		return types;
	}

	@AuraEnabled(cacheable=true)
	public static List<String> getProductFamilies() {
		List<String> families = new List<String>();
		List<Schema.PicklistEntry> picklistValues = Product__c.Family__c.getDescribe().getPicklistValues();

		for (Schema.PicklistEntry picklistValue : picklistValues) {
			families.add(picklistValue.getValue());
		}

		return families;
	}
}