src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family 1</fullName>
                </value>
                <value>
                    <fullName>Family 2</fullName>
                </value>
                <value>
                    <fullName>Family 3</fullName>
                </value>
                <value>
                    <fullName>Family 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type 1</fullName>
                </value>
                <value>
                    <fullName>Type 2</fullName>
                </value>
                <value>
                    <fullName>Type 3</fullName>
                </value>
                <value>
                    <fullName>Type 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/orderFilterTest.cls
@isTest
public class orderFilterTest {
	@isTest
	static void testGetProductTypes() {

		Product__c product = new Product__c(Type__c = 'Type 1');
		insert product;


		List<String> productTypes = orderFilter.getProductTypes();


		System.assertEquals(1, productTypes.size());
		System.assertEquals('Type 1', productTypes[0]);
	}

	@isTest
	static void testGetProductFamilies() {

		Product__c product = new Product__c(Family__c = 'Family 1');
		insert product;


		List<String> productFamilies = orderFilter.getProductFamilies();


		System.assertEquals(1, productFamilies.size());
		System.assertEquals('Family 1', productFamilies[0]);
	}
}